# Praktikum 1

Praktikum 1 ini akan membuat JST sederhana (2 layer) dengan forward pass dan backpropagation manual.

Backpropagation adalah sebuah algoritma untuk melatih jaringan saraf tiruan dengan cara mengoreksi kesalahan. Algoritma ini bekerja dengan cara menghitung selisih antara keluaran yang dihasilkan jaringan dan keluaran yang seharusnya (kesalahan), lalu memperbarui bobot dan bias jaringan secara berulang dari keluaran ke masukan untuk meminimalkan kesalahan tersebut. Cara kerja backpropagation
- Perambatan maju (forward pass): Data masukan diproses melalui jaringan dari lapisan masukan ke lapisan keluaran untuk menghasilkan prediksi awal.
- Hitung kesalahan: Selisih antara keluaran prediksi dan keluaran target dihitung menggunakan fungsi kerugian.
- Perambatan mundur (backward pass): Kesalahan disebarkan kembali ke belakang melalui jaringan dari lapisan keluaran ke lapisan masukan untuk menghitung gradien atau turunan parsial dari fungsi kerugian terhadap bobot dan bias.
- Perbarui bobot: Bobot dan bias disesuaikan menggunakan algoritma penurunan gradien untuk mengurangi kesalahan pada iterasi berikutnya.

Langkah:
1. Buat dataset sederhana (XOR).
1. Inisialisasi bobot dan bias.
1. Implementasikan forward pass.
1. Hitung error dan lakukan backpropagation.
1. Update bobot menggunakan gradient descent.


In [5]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.27527187762152555
Epoch 1000, Loss: 0.25025737700756256
Epoch 2000, Loss: 0.2500492338139324
Epoch 3000, Loss: 0.24999179669205868
Epoch 4000, Loss: 0.24993311469725435
Epoch 5000, Loss: 0.24978637464157594
Epoch 6000, Loss: 0.24917255299630722
Epoch 7000, Loss: 0.24371831192189708
Epoch 8000, Loss: 0.18513062325589957
Epoch 9000, Loss: 0.04312028352744521
Prediksi:
[[0.12213588]
 [0.89414123]
 [0.85720389]
 [0.10559335]]


# Tugas 1
## Ubah jumlah neuron hidden layer menjadi 3.

In [6]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.399130679421523
Epoch 1000, Loss: 0.2216738385137351
Epoch 2000, Loss: 0.17434392796584305
Epoch 3000, Loss: 0.0628596553545719
Epoch 4000, Loss: 0.017923021855207447
Epoch 5000, Loss: 0.00886642028407193
Epoch 6000, Loss: 0.005626099743493698
Epoch 7000, Loss: 0.004042192796671506
Epoch 8000, Loss: 0.0031229133537520153
Epoch 9000, Loss: 0.0025292352056977036
Prediksi:
[[0.04599045]
 [0.9560928 ]
 [0.95607672]
 [0.049973  ]]


## Bandingkan hasil loss dengan konfigurasi awal.

- 2 Neuron:
    - Struktur lebih sederhana yang mampu menyelesaikan permasalahan XOR. 
    - Proses pelatihannya lebih cepat, namun fleksibilitasnya terbatas.
- 3 Neuron:
    - Menyediakan kapasitas yang lebih besar untuk mengenali pola-pola tertentu.
    - Mampu membentuk representasi yang lebih kompleks dari data.

## Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.

In [11]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2507582423318583
Epoch 1000, Loss: 0.16722519149680276
Epoch 2000, Loss: 0.16683956966417635
Epoch 3000, Loss: 0.16675641739268438
Epoch 4000, Loss: 0.16672705344918295
Epoch 5000, Loss: 0.16671073558446467
Epoch 6000, Loss: 0.1667074144587712
Epoch 7000, Loss: 0.16669531248838065
Epoch 8000, Loss: 0.16669263589356237
Epoch 9000, Loss: 0.16668914659621895
Prediksi:
[[0.33344606]
 [0.33344606]
 [0.99137173]
 [0.33344606]]


### Perbandingan Fungsi Aktivasi

- Sigmoid
  - Fungsi yang menghasilkan rentang nilai antara 0–1.
  - Cocok dipasang di output layer saat menangani klasifikasi dua kelas.
  - Rentan terhadap masalah vanishing gradient saat jaringan semakin dalam.
- ReLU
  - Mengeluarkan 0 bila input negatif, atau nilai itu sendiri bila positif.
  - Proses pembelajaran lebih cepat dan hampir bebas vanishing gradient.
  - Umumnya dipilih untuk hidden layer.
